name: Release candidate

on:
  workflow_dispatch: {}

jobs:
  rc:
    name: Trigger release candidate build
    runs-on: ubuntu-latest
    container: public.ecr.aws/eksctl/eksctl-build:b06c1f3d2a18a98695327e6f8da535ded95083b7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.EKSCTLBOT_TOKEN }}
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Setup identity as eksctl-bot
        uses: ./.github/actions/setup-identity
        with:
          token: "${{ secrets.EKSCTLBOT_TOKEN }}"
      - name: Push tag and open PR to default branch
        run: make prepare-release-candidate
